set_property -dict {PACKAGE_PIN AL31 IOSTANDARD LVCMOS18} [get_ports sys_clk_in]
set_property -dict {PACKAGE_PIN AK33 IOSTANDARD LVCMOS18} [get_ports sys_rst_n]
set_property -dict {PACKAGE_PIN AL28 IOSTANDARD LVCMOS18} [get_ports {seg_cs_pin[7]}]
set_property -dict {PACKAGE_PIN AK26 IOSTANDARD LVCMOS18} [get_ports {seg_cs_pin[6]}]
set_property -dict {PACKAGE_PIN AK27 IOSTANDARD LVCMOS18} [get_ports {seg_cs_pin[5]}]
set_property -dict {PACKAGE_PIN AJ26 IOSTANDARD LVCMOS18} [get_ports {seg_cs_pin[4]}]
set_property -dict {PACKAGE_PIN AJ27 IOSTANDARD LVCMOS18} [get_ports {seg_cs_pin[3]}]
set_property -dict {PACKAGE_PIN AG25 IOSTANDARD LVCMOS18} [get_ports {seg_cs_pin[2]}]
set_property -dict {PACKAGE_PIN AH25 IOSTANDARD LVCMOS18} [get_ports {seg_cs_pin[1]}]
set_property -dict {PACKAGE_PIN AH24 IOSTANDARD LVCMOS18} [get_ports {seg_cs_pin[0]}]
set_property -dict {PACKAGE_PIN AK28 IOSTANDARD LVCMOS18} [get_ports {seg_data_0_pin[0]}]
set_property -dict {PACKAGE_PIN AL30 IOSTANDARD LVCMOS18} [get_ports {seg_data_0_pin[1]}]
set_property -dict {PACKAGE_PIN AL29 IOSTANDARD LVCMOS18} [get_ports {seg_data_0_pin[2]}]
set_property -dict {PACKAGE_PIN AM31 IOSTANDARD LVCMOS18} [get_ports {seg_data_0_pin[3]}]
set_property -dict {PACKAGE_PIN AK29 IOSTANDARD LVCMOS18} [get_ports {seg_data_0_pin[4]}]
set_property -dict {PACKAGE_PIN AJ29 IOSTANDARD LVCMOS18} [get_ports {seg_data_0_pin[5]}]
set_property -dict {PACKAGE_PIN AN30 IOSTANDARD LVCMOS18} [get_ports {seg_data_0_pin[6]}]
set_property -dict {PACKAGE_PIN AM30 IOSTANDARD LVCMOS18} [get_ports {seg_data_0_pin[7]}]
set_property -dict {PACKAGE_PIN AK31 IOSTANDARD LVCMOS18} [get_ports {seg_data_1_pin[0]}]
set_property -dict {PACKAGE_PIN AJ30 IOSTANDARD LVCMOS18} [get_ports {seg_data_1_pin[1]}]
set_property -dict {PACKAGE_PIN AP31 IOSTANDARD LVCMOS18} [get_ports {seg_data_1_pin[2]}]
set_property -dict {PACKAGE_PIN AP30 IOSTANDARD LVCMOS18} [get_ports {seg_data_1_pin[3]}]
set_property -dict {PACKAGE_PIN AM33 IOSTANDARD LVCMOS18} [get_ports {seg_data_1_pin[4]}]
set_property -dict {PACKAGE_PIN AL33 IOSTANDARD LVCMOS18} [get_ports {seg_data_1_pin[5]}]
set_property -dict {PACKAGE_PIN AN32 IOSTANDARD LVCMOS18} [get_ports {seg_data_1_pin[6]}]
set_property -dict {PACKAGE_PIN AM32 IOSTANDARD LVCMOS18} [get_ports {seg_data_1_pin[7]}]
set_property PACKAGE_PIN P2 [get_ports {sw_pin[4]}]
set_property PACKAGE_PIN N4 [get_ports {sw_pin[1]}]
set_property PACKAGE_PIN V5 [get_ports {dip_pin[4]}]
set_property PACKAGE_PIN R3 [get_ports {dip_pin[2]}]
set_property PACKAGE_PIN T5 [get_ports {dip_pin[0]}]
set_property -dict {PACKAGE_PIN AF24 IOSTANDARD LVCMOS18} [get_ports {led_pin[0]}]
set_property -dict {PACKAGE_PIN AP27 IOSTANDARD LVCMOS18} [get_ports {led_pin[1]}]
set_property -dict {PACKAGE_PIN AN27 IOSTANDARD LVCMOS18} [get_ports {led_pin[2]}]
set_property -dict {PACKAGE_PIN AP26 IOSTANDARD LVCMOS18} [get_ports {led_pin[3]}]
set_property -dict {PACKAGE_PIN AP25 IOSTANDARD LVCMOS18} [get_ports {led_pin[4]}]
set_property -dict {PACKAGE_PIN AN28 IOSTANDARD LVCMOS18} [get_ports {led_pin[5]}]
set_property -dict {PACKAGE_PIN AM28 IOSTANDARD LVCMOS18} [get_ports {led_pin[6]}]
set_property -dict {PACKAGE_PIN AN25 IOSTANDARD LVCMOS18} [get_ports {led_pin[7]}]
set_property -dict {PACKAGE_PIN AM25 IOSTANDARD LVCMOS18} [get_ports {led_pin[8]}]
set_property -dict {PACKAGE_PIN AP29 IOSTANDARD LVCMOS18} [get_ports {led_pin[9]}]
set_property -dict {PACKAGE_PIN AN29 IOSTANDARD LVCMOS18} [get_ports {led_pin[10]}]
set_property -dict {PACKAGE_PIN AM27 IOSTANDARD LVCMOS18} [get_ports {led_pin[11]}]
set_property -dict {PACKAGE_PIN AM26 IOSTANDARD LVCMOS18} [get_ports {led_pin[12]}]
set_property -dict {PACKAGE_PIN AL26 IOSTANDARD LVCMOS18} [get_ports {led_pin[13]}]
set_property -dict {PACKAGE_PIN AL25 IOSTANDARD LVCMOS18} [get_ports {led_pin[14]}]
set_property -dict {PACKAGE_PIN AJ25 IOSTANDARD LVCMOS18} [get_ports {led_pin[15]}]

set_property IOSTANDARD LVCMOS18 [get_ports {dip_pin[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dip_pin[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw_pin[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw_pin[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw_pin[0]}]
