# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/lessons/大二下/计算机组成/lab/lab3/lab3/lab3/zip_lab3 sc_computer/zip_lab3 sc_computer/constr/sc_computer_iotest.xdc

# IP: ip/lpm_rom_irom/lpm_rom_irom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lpm_rom_irom || ORIG_REF_NAME==lpm_rom_irom} -quiet] -quiet
