# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/lenovo/Desktop/computer composition project/lab1/sc_computer_iotest.xdc

# IP: ip/irom/irom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==irom || ORIG_REF_NAME==irom} -quiet] -quiet
